name       : gtkspell3
version    : 3.0.7
release    : 1
source     :
    - http://gtkspell.sourceforge.net/download/gtkspell3-3.0.7.tar.gz : 13f2e6d3e2554cc24253ef592074b28c117db33b7a4465c98c69a3e0a4fa3cc2
license    : GPL-2.0
summary    : GTK+ Spell check widget
description: |
    GtkSpell is a library which provides MSWord/MacOSX-style highlighting of
    misspelled words in a GtkTextView widget. Right-clicking a misspelled word pops
    up a menu of suggested replacements.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %configure --disable-static \
               --enable-gtk3 \
               --enable-vala \
               --enable-iso_codes
build      : |
    %make
install    : |
    %make_install
